# Generated by Django 4.2 on 2023-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_remove_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.CharField(default='alauddin', max_length=255),
            preserve_default=False,
        ),
    ]
