# Generated by Django 4.2 on 2023-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='registration_type',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
