# Generated by Django 4.2 on 2023-11-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_rename_registration_type_attendee_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='phone',
            field=models.CharField(default=771773440, max_length=255),
            preserve_default=False,
        ),
    ]
